file_format: "1"
id: spky
name: SPKY
type: shield
url: https://github.com/hypan599/zmk-xpandi.git
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - spky_left
  - spky_right
